version: '3'

services:
  tageveryone_telegrambot:
    image: matt0550/tageveryone_telegrambot
    environment:
      - token=5942137254:AAH9ScFyJFregxKxZ6DJG6SFoc-9lHIayOQ
      - owner_id=313344916
      - enable_webapp_server=True
      - webserver_debug=False
      - report_errors_owner=False
      - secret_key=36621bfedd370031c5cf0dc79f0139d805fe3182be3034ab63d98795c794
      - PUID=1000     # UID of the user inside the container, make sure it has access to the database file
      - PGID=1000     # GID of the user inside the container, make sure it has access to the database file
    ports:
      - 5000:5000
    restart: unless-stopped
